// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsyqowfqvpkuxnaabwmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzeXFvd2ZxdnBrdXhuYWFid21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NDMxMDEsImV4cCI6MjA1MzQxOTEwMX0.mSDt6pHQAZvLn9VqiOEYhdK-kdkgWXhDSFrF3p0zGwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);